[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vampires_control"
description = "VAMPIRES control software"
readme = "README.md"
license = {file = "LICENSE"}
authors = [{name = "Miles Lucas", email = "mdlucas@hawaii.edu"}]
requires-python = ">=3.7"
dependencies = [
    "docopt==0.6.*",
    "numpy==1.*",
    "scxconf",
    "swmain>=1",
    "scxkw==0.1",
    "tqdm==4.*",
    "device_control",
    "rich",
    "pyzmq"
]
dynamic = ["version"]

[project.optional-dependencies]
test = ["pytest==7.*", "mock-serial==0.0.*", "pytest-cov==4.*"]
docs = ["sphinx>=4.5,<5", "sphinx-rtd-theme==1.*", "myst-parser==0.18.*"]

[project.scripts]
"acquire" = "vampires_control.acquisition.acquire:main"
vampires_qwp_daemon = "vampires_control.daemons.qwp_daemon:main"
vampires_sdi_daemon = "vampires_control.daemons.sdi_daemon:main"
vampires_temp_daemon = "vampires_control.daemons.temp_poll_daemon:main"
vampires_status = "vampires_control.daemons.status:main"

[tool.setuptools.dynamic]
version = {attr = "vampires_control.__version__"}

[tool.pytest.ini_options]
log_cli = false
log_cli_level = "DEBUG"
log_cli_format = "[%(levelname)s] (%(name)-15s) %(message)s"

[tool.coverage.run]
source = ["vampires_control"]