[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vampires_control"
description = "VAMPIRES control software"
readme = "README.md"
license = {file = "LICENSE"}
authors = [{name = "Miles Lucas", email = "mdlucas@hawaii.edu"}]
requires-python = ">=3.7"
dependencies = [
    "docopt",
    "numpy",
    "scxconf",
    "swmain",
    "scxkw",
    "tqdm",
    "device_control",
    "rich",
    "pyzmq",
    "trogon",
]
dynamic = ["version"]

[project.optional-dependencies]
test = ["pytest", "pytest-cov"]
docs = ["sphinx", "sphinx-rtd-theme", "myst-parser", "sphinx-autobuild"]

[project.scripts]
launch_daemons = "vampires_control.launch:main"
acquire = "vampires_control.acquisition.acquire:main"
vampires_qwp_daemon = "vampires_control.daemons.qwp_daemon:main"
vampires_sdi_daemon = "vampires_control.daemons.sdi_daemon:main"
vampires_temp_daemon = "vampires_control.daemons.temp_poll_daemon:main"
vampires_status = "vampires_control.status:main"

[tool.setuptools.dynamic]
version = {attr = "vampires_control.__version__"}

[tool.pytest.ini_options]
log_cli = false
log_cli_level = "DEBUG"
log_cli_format = "[%(levelname)s] (%(name)-15s) %(message)s"

[tool.coverage.run]
source = ["vampires_control"]